name: NCTL Scan Terraform Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  NCTL-Scan-Terraform:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: NCTL-scan-installer - Terraform
        run: |
          curl -LO https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.0.2/nctl_4.0.2\_linux_arm64.zip
          unzip nctl_4.0.2_linux_arm64.zip
          cd nctl_4.0.2_linux_arm64.zip
          chmod u+x nctl
          sudo mv nctl /usr/local/bin/nctl

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Check nctl version
        run: nctl version

      - name: NCTL Scan - Terraform
        run:     
          nctl scan terraform --policies policy/validate-tags.yaml --resources oci-tf-module/validate-tags/main.tf     

      - run: echo "🍏 This job's status is ${{ job.status }}."
