name: NCTL Scan Terraform Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  NCTL-Scan-Terraform:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4


      - name: NCTL-scan-installer - Terraform
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.0.2/nctl_4.0.2\_macos_64-bit.zip'
          name: 'nctl'
          version: '4.0.2'

      - name: Check nctl version
        run: nctl version

      - name: NCTL Scan - Terraform
        run:     
          nctl scan terraform --policies policy/validate-tags.yaml --resources oci-tf-module/validate-tags/main.tf     

      - run: echo "🍏 This job's status is ${{ job.status }}."
